services:
  postgres:
    image: postgres:18
    container_name: book_database_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d books"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  javalibrary:
    build: .
    container_name: book_service
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env  # <-- Загрузит все переменные из .env файла
    environment:
      BOOK_DB_URL: jdbc:postgresql://postgres:5432/books
      BOOK_DB_USERNAME: postgres
      BOOK_DB_PASSWORD: postgres
    restart: no
