services:
  book-postgres:
    image: postgres:18
    container_name: book-database-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d books"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - library-network

  book-service:
    build: .
    container_name: book-service
    ports:
      - "8090:8090"
    depends_on:
      book-postgres:
        condition: service_healthy
    environment:
      BOOK_DB_URL: jdbc:postgresql://book-postgres:5432/books
      BOOK_DB_USERNAME: postgres
      BOOK_DB_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - library-network

networks:
  library-network:
    external: true
    name: library-network
